INSERT INTO `aspirations` VALUES
(1,'Doce coração de Jesus, sede o meu amor!','Jesus'),
(2,'Doce coração de Maria, sede a minha salvação!','Santa Maria'),
(3,'Senhor, tratai o vosso servo segundo vossa misericórdia!','Deus Pai'),
(4,'Pai santo e onipotente, Deus eterno e misericordioso: por intercessão da Bem-aventurada Virgem Maria, dou-Vos graças por todos os vossos benefícios, mesmo desconhecidos','Deus Pai'),
(5,'Coração sacratíssimo e misericordioso de Jesus, dai-nos a paz!','Jesus'),
(6,'Coração dulcíssimo de Maria, preparai-nos um caminho seguro!','Santa Maria'),
(7,'Louvemos o Pai e o Filho com o Espírito Santo!','Santíssima Trindade'),
(8,'Senhor, que eu veja! Senhor, faça-se! Senhora, que eu veja! Senhora, faça-se!','Jesus'),
(9,'Senhor, Tu sabes tudo, Tu sabes que eu te amo!','Jesus'),
(10,'Sou Teu, para Ti nasci, que queres, Jesus de mim?','Jesus'),
(11,'Jesus, eu te amo.','Jesus'),
(12,'Glória ao Pai, Glória ao Filho, Glória ao Espírito Santo. Glória a Santa Maria e também a São José. Obrigado aos Anjos que te fazem a corte.','Santíssima Trindade'),
(13,'Senhor, abandono-me em Ti, confio em Ti, descanso em Ti.','Deus Pai'),
(14,'Creio em Deus Pai, creio em Deus Filho, Creio em Deus Espírito Santo. Espero em Deus pai, espero em Deus Filho, espero em Deus Espírito Santo. Amo Deus Pai, amo Deus Filho, amo Deus Espírito Santo.','Santíssima Trindade'),
(15,'Jesus, Jesus, sede sempre para mim, Jesus.','Jesus'),
(16,'Tu és sacerdote para sempre!','Jesus'),
(17,'O que for bom aos olhos de Deus, faça-se!','Deus Pai'),
(18,'Mostrai que sois mãe!','Santa Maria'),
(19,'Mãe, minha mãe!','Santa Maria'),
(20,'Santa Maria, nosso refúgio e fortaleza!','Santa Maria'),
(21,'Santa Maria, detém o teu dia.','Santa Maria'),
(22,'Santa Maria, ajudai os vossos filhos, ajudai as vossas filhas!','Santa Maria'),
(23,'Santa Maria, Esperança nossa, Sede da Sabedoria, rogai por nós!','Santa Maria'),
(24,'Santa Maria, Esperança nossa, Escrava do Senhor, ajudai as vossas filhas!','Santa Maria'),
(25,'Santa Maria, Rainha do Opus Dei, ajudai os vossos filhos!','Santa Maria'),
(26,'Santa Maria, Estrela do Oriente, ajudai os vossos filhos!','Santa Maria'),
(27,'O Senhor esteja contigo!','Deus Pai'),
(28,'Nossos santos Anjos da Guarda, defendei-nos!','Anjo da Guarda'),
(29,'São José, Nosso Pai e Senhor, abençoai todos os filhos da Santa Igreja de Deus!','Santos'),
(30,'Vamos com confiança até o trono da glória, a fim de obtermos misericórdia!','Fé'),
(31,'Ave Maria puríssima, sem pecado concebida.','Santa Maria'),
(32,'À Vossa proteção nos acolhemos, não desprezeis as nossas súplicas.','Santa Maria'),
(33,'Bendita seja a Mãe que te trouxe ao mundo.','Santa Maria'),
(34,'Coração de Maria dolorosa, tende misericórdia de nós, tende misericórdia de mim!','Santa Maria'),
(35,'Mãe bem-aventurada e Virgem intacta, intercedei por nós!','Santa Maria'),
(36,'Tudo é para bem!','Humildade'),
(37,'Sempre como um burrinho!','Humildade'),
(38,'Senhor, quero estar ao teu lado como um burrinho, mas Tu me tomaste pelo cabresto, levaste-me para diante e me receberás na tua glória.','Humildade'),
(39,'Faça-se, cumpra-se, seja louvada e eternamente glorificada a justíssima e amabilíssima vontade de Deus sobre todas as coisas. Assim seja. Assim seja.','Humildade'),
(40,'Creio mais do que se Te visse com meus olhos, mais do que se Te escutasse com os meus ouvidos, mais do que se Te tocasse com as minhas mãos.','Fé'),
(41,'Permaneçamos sempre em ação de graças!','Fé'),
(42,'As montanhas derreteram-se como cera diante do Senhor.','Fé'),
(43,'Os que me causam tribulações, meus inimigos, adoeceram e sucumbiram.','Humildade'),
(44,'Somos servos inúteis; fizemos o que deveríamos fazer.','Humildade'),
(45,'Convém orar sempre e não desfalecer.','Fé'),
(46,'Queima-nos com o fogo do Espírito Santo!','Espírito Santo'),
(47,'Vinde, Espírito Santo, enchei o coração de vossos fieis e acendei neles o fogo do vosso amor!','Espírito Santo'),
(48,'Convém que Ele cresça e eu diminua.','Humildade'),
(49,'São Miguel Arcanjo, defendei-nos no combate; protegei-nos contra a maldade e ciladas do demônio. Assim lhe ordene Deus, humildemente o suplicamos. E vós, Príncipe da milícia celeste, precipitai no inferno, pelo poder divino, Satanás e os outros espíritos malignos que vagueiam pelo mundo para perder as almas.','Anjo da Guarda'),
(50,'Oremos pelo nosso Beatíssimo Papa. O Senhor o conserve, e lhe dê vida, e o faça feliz na terra, e não o deixe cair nas mãos dos seus inimigos.','Papa'),
(51,'Meu Deus! Que eu odeie o pecado e me una a Ti, abraçando-me à Santa Cruz, para cumprir por minha vez a tua Vontade amabilíssima..., nu de todo afeto terreno, sem outras miras que a tua glória..., generosamente sem reservar nada para mim, oferecendo-me contigo em perfeito holocausto.','Deus Pai'),
(52,'Vinde, ó Espírito Santo! Iluminai o meu entendimento para que conheça os vossos preceitos; fortalecei o meu coração contra as insídias do inimigo, inflamai a minha vontade... Ouvi a vossa voz e não quero endurecer-me e resistir, dizendo: depois..., amanhã. Agora!, não suceda que o amanhã me venha a faltar. Ó Espírito de verdade e de sabedoria, Espírito de entendimento e de conselho, Espírito de gozo e de paz! Quero o que quiserdes, quero porque o quereis, quero como quiserdes, quero quando quiserdes...','Espírito Santo'),
(53,'Jesus! Que eu nunca mais Te perca...','Jesus'),
(54,'Jesus, filho de Davi, tem compaixão de mim!','Jesus'),
(55,'Jesus manso e humilde de coração, fazei o nosso coração semelhante ao Vosso.','Jesus'),
(56,'Ó meu Deus, criai em mim um coração puro e renovai-me o espírito de firmeza.','Deus Pai,Espírito Santo'),
(57,'Senhor, protegei-me no dia de hoje para que não vos venda nem vos traia.','Deus Pai'),
(58,'Senhor, protege-me. Se não me ajudares, vou trair-te hoje mesmo.','Deus Pai'),
(59,'Ó Maria, concebida sem pecado, rogai por nós que recorremos a Vós!','Santa Maria'),
(60,'Depois do parto, ó Virgem, permaneceste intacta: Mãe de Deus, intercedei por nós!','Santa Maria'),
(61,'Meu Deus, obrigado, obrigado por tudo: pelo que me contraria, pelo que não entendo, pelo que me faz sofrer.','Deus Pai,Humildade'),
(62,'Senhor, meu Deus! Em tuas mãos abandono o passado, o presente e o futuro, o pequeno e o grande, o pouco e o muito, o temporal e o eterno.','Deus Pai,Abandono'),
(63,'Eu subirei com eles até junto da Cruz e despregá-lo-ei com os meus desagravos e mortificações...','Cruz,Jesus'),
(64,'Eu subirei com eles até junto da Cruz e envolvê-lo-ei com o lençol novo da minha vida limpa...','Cruz,Jesus'),
(65,'Eu subirei com eles até junto da Cruz e o enterrarei em meu peito de rocha viva, donde ninguém mo poderá arrancar - e aí, Senhor, descansai!','Cruz,Jesus'),
(66,'Santa Mãe de Deus, que eu recorra a vós após ter fugido do sofrimento e da Cruz!','Santa Maria,Cruz'),
(67,'Consoladora dos Aflitos, ajudai-me para que após fugir da Cruz, como os discípulos, possa, também arrependido como eles, unir-me de novo aos meus irmãos.','Santa Maria,Cruz'),
(68,'Meu Deus, que ninguém sofra ou se perca por minha culpa.','Deus Pai'),
(69,'Senhor, para mim nada quero. Tudo para tua glória e por Amor.','Deus Pai,Humildade'),
(70,'Jesus, Tu que curastes tantas almas, faz com que te veja como Médico Divino na Hóstia Santa!','Jesus,Eucaristia'),
(71,'Bendita seja a Santíssima Trindade.','Santíssima Trindade'),
(72,'Meu Deus e meu tudo!','Deus Pai'),
(73,'Ó Deus, compadecei-Vos de mim, pecador.','Deus Pai,Humildade'),
(74,'Tu és o meu Deus, eu Te confessarei; Tu és o meu Deus, eu Te glorificarei.','Fé'),
(75,'Ó meu Deus: cada dia me sinto menos seguro de mim e mais seguro de Ti!','Abandono,Humildade'),
(76,'Tudo refiro a Ti, meu Deus. Sem Ti, que és meu Pai, que seria de mim?','Abandono,Humildade'),
(77,'Dá-me, Senhor, o amor com que queres que eu Te ame!','Amor'),
(78,'Senhor, o que Tu quiseres..., eu o amo!','Abandono,Amor'),
(79,'Cristo vence! Cristo reina! Cristo impera!','Jesus'),
(80,'Tu o queres, Senhor?... Eu também o quero!','Abandono'),
(81,'Senhor, se quiseres, podes limpar-me.','Jesus,Abandono,Humildade'),
(82,'Não desprezarás, Senhor, um coração contrito e humilhado.','Fé,Abandono,Humildade'),
(83,'Aproximemo-nos com fé do trono da graça para alcançarmos misericórdia e encontrarmos a graça no momento oportuno.','Fé'),
(84,'És toda formosa, Maria, e não há em Ti mancha de pecado.','Santa Maria'),
(85,'São José, chefe da Sagrada Família, rogai pela nossa família.','São José'),
(86,'Eu vos amo, Jesus e Maria! Jesus e Maria, eu vos dou meu coração e minha alma!','Jesus,Santa Maria,Amor,Abandono'),
(87,'Quanto a mim, sou pobre e desvalido. Socorrei-me, ó Deus, sois meu protetor e libertador. Senhor, não tardeis mais.','Abandono,Humildade'),
(88,'Ó Espirito Santo, vem ao meu coração!','Espírito Santo'),
(89,'Ó Deus, arrasta meu coração para ti e dá-me a a caridade e o temor.','Deus Pai'),
(90,'Ó Cristo, protege-me de todo mau pensamento, aquece-me e inflama-me com o teu doce amor, de modo que toda pena me pareça leve.','Jesus'),
(91,'Meu Pai santo e meu doce Senhor, ajuda-me agora e em qualquer necessidade. Cristo amor. Cristo amor.','Deus Pai,Jesus');
